config/routes.rb
Rails.application.routes.draw do
 mount Payify::Engine => '/payify', as: 'payify'

  devise_for :users
  root to: "rooms#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "/tarifs", to: "pages#tarifs"
  get "/centre_bien_etre", to: "pages#centre_bien_etre"
  get "/profile", to: "dashboard#user_profile"


  resources :rooms do
    resources :bookings do
      member do
        get "payment"
      end

    end

    resources :reviews
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  include ::Payify::HasPaymentConcern
  after_save :create_payment
  belongs_to :room
  belongs_to :user



  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :number_of_adults, presence: true


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :phone_number, presence: true
  validates :civility, presence: true


  def amount_to_pay
    total_price
  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :bookings
  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_room, only: [:new, :create]

  def payment

    if @booking.payment_pending?
      @booking.payment.stripe_init_intent
    end
  end

  def new
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.room = Room.find(params[:room_id])

    # Vérification du nombre de personnes par rapport à la capacité de la chambre
    if @booking.number_of_adults + @booking.number_of_childs > @booking.room.number_of_guests
      flash[:alert] = "You can't book more guests than the room can host"
      return render :new
    end

    if @booking.save
      # Crée et sauvegarde un paiement via Payify
     redirect_to room_booking_path(@room, @booking)
      else
        # Si le paiement échoue, retourner au formulaire de réservation
        flash[:alert] = "Erreur lors de la création de la réservation"
        render :new


    end
  end


  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :number_of_adults, :total_price, :first_name, :last_name, :email, :phone_number, :number_of_childs, :civility)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def user_profile
    @user = current_user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def centre_bien_etre
  end

  def tarifs
    @rooms = Room.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all

  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<!-- **************** MAIN CONTENT START **************** -->
<main>

<!-- =======================
Page banner START -->
<section class="py-0">
	<div class="container">
		<!-- Card START -->
		<div class="card bg-light overflow-hidden border-0 px-sm-5 rounded-5 mb-5 mt-5">
			<div class="row align-items-center g-4">

				<!-- Content -->
				<div class="col-sm-9">
					<div class="card-body">

						<!-- Title -->
						<h1 class="m-0 h2 card-title title-font text-success">Votre réservation</h1>
					</div>
				</div>

				<!-- Image -->
				<div class="col-sm-3 text-end d-none d-sm-block">
					<%= image_tag '17.svg', alt: '', class: 'w-75 h-75'%>
				</div>
			</div>
		</div>
		<!-- Card END -->
	</div>
</section>
<!-- =======================
Page banner END -->

<!-- =======================
Page content START -->
<section  data-controller="total-price"   data-total-price-priceperday-value="<%= @room.price_per_day %>">
<%= simple_form_for([@room, @booking]) do |f| %>
	<div class="container" data-controller="datepicker" >
		<div class="row g-4 g-lg-5" >

			<!-- Left side content START -->
			<div class="col-xl-8">
				<div class="vstack gap-5">
					<!-- Hotel information START -->
					<div class="card shadow bg-white rounded-5">
						<!-- Card header -->
						<div class="card-header p-4 border-0 bg-white mb-0 rounded-5">
							<!-- Title -->
							<h3 class="mb-0 title-font text-success"><i class="fa-solid fa-hotel me-2 text-success mt-3 "></i>Informations séjour</h3>
						</div>

						<!-- Card body START -->
						<div class="card-body p-4">
							<!-- Card list START -->
							<div class="card mb-2 border-0 bg-white">
								<div class="row align-items-center">
									<!-- Image -->
									<div class="col-sm-6 col-md-3">
                    <%= image_tag "test2.jpg", alt: '', class: 'card-img rounded-5 w-100 h-100' %>

									</div>

									<!-- Card Body -->
									<div class="col-sm-6 col-md-9">
										<div class="card-body pt-3 pt-sm-0 p-0">
											<!-- Title -->
											<h5 class="card-title"><%= @room.name %></h5>


											<!-- Rating star -->
											<ul class="list-inline mb-0">
												<li class="list-inline-item me-0 small"><i class="fa-solid fa-star text-warning"></i></li>
												<li class="list-inline-item me-0 small"><i class="fa-solid fa-star text-warning"></i></li>
												<li class="list-inline-item me-0 small"><i class="fa-solid fa-star text-warning"></i></li>
												<li class="list-inline-item me-0 small"><i class="fa-solid fa-star text-warning"></i></li>
												<li class="list-inline-item me-0 small"><i class="fa-solid fa-star-half-alt text-warning"></i></li>
												<li class="list-inline-item ms-2 h6 small fw-bold mb-0">4.5/5.0</li>
											</ul>
										</div>
									</div>

								</div>
							</div>
							<!-- Card list END -->

              <div class="container2">
							<!-- Information START -->

							<div class="row g-4 mt-4" data-controller="datepicker"   >


								<!-- Item -->
								<div class="col-lg-6">
									<div class="bg-light py-3 px-4 rounded-5">
                 <%= f.input :check_in, as: :string, input_html: {type: 'date', data: { datepicker_target: "startInput" , total_price_target: 'startDate' }  } %>									</div>
								</div>

								<!-- Item -->
								<div class="col-lg-6">
									<div class="bg-light py-3 px-4 rounded-5">
                  <%= f.input :check_out, as: :string, input_html: { data: { datepicker_target: "endInput", total_price_target: "endDate", action: 'change->total-price#calculPrice' } } %>
									</div>
								</div>

								<!-- Item -->

							</div>
              <div class="row g-4 mt-3" >
              <div class="col-lg-6">
									<div class="bg-light py-3 px-4 rounded-3">
                    <%= f.input :number_of_adults, label: "Nombre d'adultes", as: :integer, input_html: { class: ''}  %>
									</div>
								</div>
                <div class="col-lg-6">
              <div class="bg-light py-3 px-4 rounded-3">
                    <%= f.input :number_of_childs, label: "Nombre d'enfants", as: :integer, input_html: { class: ''}  %>
									</div>
              </div>
              </div>
							<!-- Information END -->
              </div>

							<!-- Card START -->
							<div class="card border mt-4 rounded-5 bg-white">
								<!-- Card header -->
								<div class="card-header border-bottom rounded-5 bg-white d-md-flex justify-content-md-between">
									<h5 class="card-title mb-2 mt-2 title-font text-success">Prestations et Services</h5>
									<a href="#" class="btn btn-link text-decoration-none p-0 mb-2 mt-2">Voir la politique d'annulation</a>
								</div>

								<!-- Card body -->
								<div class="card-body">
									<h6 class ="fw-bold title-font">Le prix inclue</h6>
									<!-- List -->
									<ul class="list-group list-group-borderless mb-0">
										<li class="list-group-item border-0 bg-white h6 fw-light d-flex mb-0"><i class="bi bi-patch-check-fill text-success me-2"></i>Free Breakfast and Lunch/Dinner.</li>
										<li class="list-group-item border-0 bg-white h6 fw-light d-flex mb-0"><i class="bi bi-patch-check-fill text-success me-2"></i>Great Small Breaks.</li>
										<li class="list-group-item border-0 bg-white h6 fw-light d-flex mb-0"><i class="bi bi-patch-check-fill text-success me-2"></i>Free Stay for Kids Below the age of 12 years.</li>
										<li class="list-group-item border-0 bg-white h6 fw-light d-flex mb-0"><i class="bi bi-patch-check-fill text-success me-2"></i>On Cancellation, You will not get any refund</li>
									</ul>
								</div>
							</div>
							<!-- Card END -->
						</div>
						<!-- Card body END -->
					</div>
					<!-- Hotel information END -->

					<!-- Guest detail START -->
					<div class="card shadow bg-white rounded-5">
						<!-- Card header -->
						<div class="card-header border-bottom p-4 bg-white rounded-5">
							<h4 class="card-title mb-0 title-font text-success "><i class="fa-solid fa-users me-2" style="color: #528852;"></i>Détails invités</h4>
						</div>

						<!-- Card body START -->
						<div class="card-body p-4">
							<!-- Form START -->
							<form class="row g-4">
								<!-- Title -->
								<div class="col-12">
									<div class="bg-light rounded-2 px-4 py-3 mb-2">
										<h6 class="mb-0">Invité principal</h6>
									</div>
								</div>

								<!-- Select -->
								<div class="col-md-2">
									<div class="form-size-lg">
                    <%= f.input :civility,label: "Civilité", as: :select, collection: [["Mr", "Mr"], ["Mme", "Mme"]], include_blank: "Sélectionner" %>

									</div>
								</div>

								<!-- Input -->
								<div class="col-md-5">
								 <%= f.input :first_name, label: "Prénom", as: :string, input_html: { class: ''}  %>

								</div>

								<!-- Input -->
								<div class="col-md-5">
									<%= f.input :last_name, label: "Nom", as: :string, input_html: { class: ''}  %>
								</div>

								<!-- Input -->
								<div class="col-md-6">
									<%= f.input :email, label: "Addresse Email", as: :string, input_html: { class: ''}  %>
								</div>

								<!-- Input -->
								<div class="col-md-6">
									<%= f.input :phone_number, label: "Téléphone", as: :string, input_html: { class: ''}  %>
								</div>
							</form>
							<!-- Form END -->




						</div>
						<!-- Card body END -->
					</div>
					<!-- Guest detail END -->


				</div>
			</div>
			<!-- Left side content END -->

			<!-- Right side content START -->
			<aside class="col-xl-4">
				<div class="row g-4 sticky-top z-sticky-card" style="top: 120px">

					<!-- Price summary START -->
					<div class="col-md-6 col-xl-12 ">
						<div class="card shadow rounded-5  bg-white " >
							<!-- card header -->
							<div class="card-header border-bottom-0 rounded-5 bg-white mt-2">
								<h5 class="card-title mb-0 bg-white title-font text-success">Prix Réservation</h5>
							</div>

							<!-- Card body -->
							<div class="card-body bg-white">
								<ul class="list-group list-group-borderless">
									<li class="list-group-item bg-white border-0 d-flex justify-content-between align-items-center">
										<span class="h6 fw-light mb-0">Prix à la journée HT</span>
										<span class="fs-5" ><%= @room.price_per_day %> €</span>
									</li>
									<li class="list-group-item d-flex bg-white border-0 justify-content-between align-items-center">
										<span class="h6 fw-light mb-0">Total Discount<span class="badge text-bg-danger smaller mb-0 ms-2">10% off</span></span>
										<span class="fs-5 text-success">-$2,560</span>
									</li>
									<li class="list-group-item d-flex bg-white border-0 justify-content-between align-items-center">
										<span class="h6 fw-light mb-0">Price after discount</span>
										<span class="fs-5">$1852</span>
									</li>
									<li class="list-group-item d-flex bg-white border-0 justify-content-between align-items-center">
										<span class="h6 fw-light mb-0"></span>
										<span class="fs-5" ></span>
									</li>
								</ul>
							</div>

							<!-- Card footer -->
							<div class="card-footer border-top-0 bg-white rounded-5">
								<div class="d-flex justify-content-between align-items-center">
									<span class="h5 mb-0 title-font text-success">Prix total HT</span>
                  <%= f.input :total_price, label: false, as: :decimal, input_html: { readonly: true, class: 'w-50 p-0 fs-5 mt-4 text-center bg-white border-0 title-font text-success', data: {'total-price-target' => 'totalPrice'} } %>
                  <span class="h5 mb-0 title-font text-success" > € </span>
								</div>
                <div class="d-flex justify-content-center">
                <div>
                <%= f.submit "Je réserve mon séjour de rêve !",   class: "btn btn-primary mt-3 text-white  rounded-4 mb-2 mt-4" %>
                </div>
                </div>
							</div>
						</div>
					</div>
					<!-- Price summary END -->



				</div>
			</aside>
			<!-- Right side content END -->
		</div> <!-- Row END -->
	</div>
  <% end %>
</section>
<!-- =======================
Page content START -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

app/views/bookings/payment.html.erb
<% unless @booking.paid? || @booking.payment.nil? %>
  <%= render "payify/payments/form", payment: @booking.payment %>
<% end %>

app/views/bookings/show.html.erb
<%= render "payify/payments/form", payment: @booking.payment %>

app/views/dashboard/user_profile.html.erb
<!-- **************** MAIN CONTENT START **************** -->
<main>

<!-- =======================
Content START -->
<section class="pt-3">
	<div class="container">
		<div class="row">

			<!-- Sidebar START -->
			<div class="col-lg-4 col-xl-3">
				<!-- Responsive offcanvas body START -->
				<div class="offcanvas-lg offcanvas-end" tabindex="-1" id="offcanvasSidebar" >
					<!-- Offcanvas header -->
					<div class="offcanvas-header justify-content-end pb-2">
						<button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#offcanvasSidebar" aria-label="Close"></button>
					</div>

					<!-- Offcanvas body -->
					<div class="offcanvas-body p-3 p-lg-0">
						<div class="card bg-light w-100">

							<!-- Edit profile button -->
							<div class="position-absolute top-0 end-0 p-3">
								<a href="#" class="text-primary-hover" data-bs-toggle="tooltip" data-bs-title="Edit profile">
									<i class="bi bi-pencil-square"></i>
								</a>
							</div>

							<!-- Card body START -->
							<div class="card-body p-3">
								<!-- Avatar and content -->
								<div class="text-center mb-3">
									<!-- Avatar -->
									<div class="avatar avatar-xl mb-2">
										<img class="avatar-img rounded-circle border border-2 border-white" src="assets/images/avatar/01.jpg" alt="">
									</div>
									<h6 class="mb-0">Jacqueline Miller</h6>
									<a href="#" class="text-reset text-primary-hover small">hello@gmail.com</a>
									<hr>
								</div>

								<!-- Sidebar menu item START -->
								<ul class="nav nav-pills-primary-soft flex-column">
									<li class="nav-item">
										<a class="nav-link active" href="account-profile.html"><i class="bi bi-person fa-fw me-2"></i>My Profile</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="account-bookings.html"><i class="bi bi-ticket-perforated fa-fw me-2"></i>My Bookings</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="account-travelers.html"><i class="bi bi-people fa-fw me-2"></i>Travelers</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="account-payment-details.html"><i class="bi bi-wallet fa-fw me-2"></i>Payment Details</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="account-wishlist.html"><i class="bi bi-heart fa-fw me-2"></i>Wishlist</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="account-settings.html"><i class="bi bi-gear fa-fw me-2"></i>Settings</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="account-delete.html"><i class="bi bi-trash fa-fw me-2"></i>Delete Profile</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-danger bg-danger-soft-hover" href="#"><i class="fas fa-sign-out-alt fa-fw me-2"></i>Sign Out</a>
									</li>
								</ul>
								<!-- Sidebar menu item END -->
							</div>
							<!-- Card body END -->
						</div>
					</div>
				</div>
				<!-- Responsive offcanvas body END -->
			</div>
			<!-- Sidebar END -->

			<!-- Main content START -->
			<div class="col-lg-8 col-xl-9">

				<!-- Offcanvas menu button -->
				<div class="d-grid mb-0 d-lg-none w-100">
					<button class="btn btn-primary mb-4" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasSidebar" aria-controls="offcanvasSidebar">
						<i class="fas fa-sliders-h"></i> Menu
					</button>
				</div>

				<div class="vstack gap-4">
					<!-- Verified message -->
					<div class="bg-light rounded p-3">
						<!-- Progress bar -->
						<div class="overflow-hidden">
							<h6>Complete Your Profile</h6>
							<div class="progress progress-sm bg-success bg-opacity-10">
								<div class="progress-bar bg-success aos" role="progressbar" data-aos="slide-right" data-aos-delay="200" data-aos-duration="1000" data-aos-easing="ease-in-out" style="width: 85%" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
								<span class="progress-percent-simple h6 fw-light ms-auto">85%</span>
							</div>
						</div>
						<p class="mb-0">Get the best out of booking by adding the remaining details!</p>
						</div>
						<!-- Content -->
						<div class="bg-body rounded p-3 mt-3">
							<ul class="list-inline hstack flex-wrap gap-2 justify-content-between mb-0">
								<li class="list-inline-item h6 fw-normal mb-0"><a href="#"><i class="bi bi-check-circle-fill text-success me-2"></i>Verified Email</a></li>
								<li class="list-inline-item h6 fw-normal mb-0"><a href="#"><i class="bi bi-check-circle-fill text-success me-2"></i>Verified Mobile Number</a></li>
								<li class="list-inline-item h6 fw-normal mb-0"><a href="#" class="text-primary"><i class="bi bi-plus-circle-fill me-2"></i>Complete Basic Info</a></li>
							</ul>
						</div>
					</div>

					<!-- Personal info START -->
					<div class="card border">
						<!-- Card header -->
						<div class="card-header border-bottom">
							<h4 class="card-header-title">Personal Information</h4>
						</div>

						<!-- Card body START -->
						<div class="card-body">
							<!-- Form START -->
							<form class="row g-3">
								<!-- Profile photo -->
								<div class="col-12">
									<label class="form-label">Upload your profile photo<span class="text-danger">*</span></label>
									<div class="d-flex align-items-center">
										<label class="position-relative me-4" for="uploadfile-1" title="Replace this pic">
											<!-- Avatar place holder -->
											<span class="avatar avatar-xl">
												<img id="uploadfile-1-preview" class="avatar-img rounded-circle border border-white border-3 shadow" src="assets/images/avatar/01.jpg" alt="">
											</span>
										</label>
										<!-- Upload button -->
										<label class="btn btn-sm btn-primary-soft mb-0" for="uploadfile-1">Change</label>
										<input id="uploadfile-1" class="form-control d-none" type="file">
									</div>
								</div>

								<!-- Name -->
								<div class="col-md-6">
									<label class="form-label">Full Name<span class="text-danger">*</span></label>
									<input type="text" class="form-control" value="Jacqueline Miller" placeholder="Enter your full name">
								</div>

								<!-- Email -->
								<div class="col-md-6">
									<label class="form-label">Email address<span class="text-danger">*</span></label>
									<input type="email" class="form-control" value="hello@gmail.com" placeholder="Enter your email id">
								</div>

								<!-- Mobile -->
								<div class="col-md-6">
									<label class="form-label">Mobile number<span class="text-danger">*</span></label>
									<input type="text" class="form-control" value="222 555 666" placeholder="Enter your mobile number">
								</div>

								<!-- Nationality -->
								<div class="col-md-6">
									<label class="form-label">Nationality<span class="text-danger">*</span></label>
									<select class="form-select js-choice">
										<option value="">Select your country</option>
										<option>USA</option>
										<option selected>Paris</option>
										<option>India</option>
										<option>UK</option>
									</select>
								</div>

								<!-- Date of birth -->
								<div class="col-md-6">
									<label class="form-label">Date of Birth<span class="text-danger">*</span></label>
									<input type="text" class="form-control flatpickr" value="29 Aug 1996" placeholder="Enter date of birth" data-date-format="d M Y">
								</div>

								<!-- Gender -->
								<div class="col-md-6">
									<label class="form-label">Select Gender<span class="text-danger">*</span></label>
									<div class="d-flex gap-4">
										<div class="form-check radio-bg-light">
											<input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" checked="">
											<label class="form-check-label" for="flexRadioDefault1">
												Male
											</label>
										</div>
										<div class="form-check radio-bg-light">
											<input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2">
											<label class="form-check-label" for="flexRadioDefault2">
												Female
											</label>
										</div>
										<div class="form-check radio-bg-light">
											<input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault3">
											<label class="form-check-label" for="flexRadioDefault3">
												Others
											</label>
										</div>
									</div>
								</div>

								<!-- Address -->
								<div class="col-12">
									<label class="form-label">Address</label>
									<textarea class="form-control" rows="3" spellcheck="false">2119 N Division Ave, New Hampshire, York, United States</textarea>
								</div>

								<!-- Button -->
								<div class="col-12 text-end">
									<a href="#" class="btn btn-primary mb-0">Save Changes</a>
								</div>
							</form>
							<!-- Form END -->
						</div>
						<!-- Card body END -->
					</div>
					<!-- Personal info END -->

					<!-- Update email START -->
					<div class="card border">
						<!-- Card header -->
						<div class="card-header border-bottom">
							<h4 class="card-header-title">Update email</h4>
							<p class="mb-0">Your current email address is <span class="text-primary">example@gmail.com</span></p>
						</div>

						<!-- Card body START -->
						<div class="card-body">
							<form>
								<!-- Email -->
								<label class="form-label">Enter your new email id<span class="text-danger">*</span></label>
								<input type="email" class="form-control" placeholder="Enter your email id">

								<div class="text-end mt-3">
									<a href="#" class="btn btn-primary mb-0">Save Email</a>
								</div>
							</form>
						</div>
						<!-- Card body END -->
					</div>
					<!-- Update email END -->

					<!-- Update Password START -->
					<div class="card border">
						<!-- Card header -->
						<div class="card-header border-bottom">
							<h4 class="card-header-title">Update Password</h4>
							<p class="mb-0">Your current email address is <span class="text-primary">example@gmail.com</span></p>
						</div>

						<!-- Card body START -->
						<form class="card-body">
							<!-- Current password -->
							<div class="mb-3">
								<label class="form-label">Current password</label>
								<input class="form-control" type="password" placeholder="Enter current password">
							</div>
							<!-- New password -->
							<div class="mb-3">
								<label class="form-label"> Enter new password</label>
								<div class="input-group">
									<input class="form-control fakepassword" placeholder="Enter new password" type="password" id="psw-input">
									<span class="input-group-text p-0 bg-transparent">
										<i class="fakepasswordicon fas fa-eye-slash cursor-pointer p-2"></i>
									</span>
								</div>
							</div>
							<!-- Confirm -->
							<div class="mb-3">
								<label class="form-label">Confirm new password</label>
								<input class="form-control" type="password" placeholder="Confirm new password">
							</div>

							<div class="text-end">
								<a href="#" class="btn btn-primary mb-0">Change Password</a>
							</div>
						</form>
						<!-- Card body END -->
					</div>
					<!-- Update Password END -->
				</div>
			</div>
			<!-- Main content END -->

		</div>
	</div>
</section>
<!-- =======================
Content END -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm shadow-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <div class= "logo-section d-flex">
    <div><%= link_to rooms_path, class: "navbar-brand m-0" do %>
      <%= image_tag 'icons8-wisteria-58.png' , alt: 'Description of the image', class: 'w-75 h-50 mr-1 mt-3 md-3 mb-3' %>


    <% end %></div>

    <div class = "mt-4"><h5><%= link_to 'Gites des Glycines', rooms_path, class: ' text-decoration-none title-font text-success'%></h5></div>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>


          <li class="nav-item active">
            <%= link_to "Accueil", rooms_path, class: "nav-link hover-link title-font " %>
          </li>
          <li class="nav-item">
            <%= link_to "Nos locations", "#{rooms_path}#section-target", class: "nav-link hover-link title-font " %>
          </li>
          <li class="nav-item">
            <%= link_to "Tarifs", tarifs_path, class: "nav-link hover-link title-font " %>
          </li>
          <li class="nav-item">
            <%= link_to "Centre de bien-être", centre_bien_etre_path , class: "nav-link hover-link title-font " %>
          </li>

             <li class="nav-item active ms-5">
            <p><strong><%= link_to current_user.first_name, "#" , class: "nav-link" %></strong></p>
            </li>

          <li class="nav-item dropdown mb-3 mt-2 ms-2">

            <i class="fa-solid fa-circle-user fa-2xl" style="color: #528852;" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", profile_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              <%= link_to "Se déconnecter ", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>

            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>